### ISSUE TITLE
Link auf Raw-Datei

### ISSUE THREAD

**Issue by TobiasNx** [elena1113/MetadatenDMT#1]
![grafik](https://user-images.githubusercontent.com/61879957/172385656-42bce99e-e733-4c15-b854-8d9f14d38799.png)

Wir benötigen die raw-Version der JSON-Datei. Sie findet sich unter diesem Knopf. Ich habe dazu einen PR vorgeschlagen:
https://github.com/elena1113/MetadatenDMT/pull/2

**Comment by elena1113** [comment]
fixed with commit 377b2095803d00305663ae6c2fbd3879c6743faa
